name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:
  schedule:
    # Runs on the first day of every month at 12:00 UTC (noon)
    - cron: "0 12 1 * *"

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run MDN scraper
        run: uv run scraper.py
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - id: deployment
        uses: actions/deploy-pages@v4
